version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-node
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - DB_HOST=db-mysql
      - DB_USER=root
      - DB_PASSWORD=secret_password
      - DB_NAME=infraestructura_db
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:8.0
    container_name: mysql-contenedor
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret_password
      - MYSQL_DATABASE=infraestructura_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: