POST https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/usuarios
Content-Type: application/json

{
  "nombre": "Jossse EstoyartoJefe",
  "correo": "sss@gmail.com",
  "password": "ss111"
}

### Obtener todos los usuarios (GET)
GET https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/usuarios

### 3. Actualizar un usuario (PUT)
PUT https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/usuarios/5
Content-Type: application/json

{
    "nombre": "Saturnino",
    "correo": "Saturnino@ejemplo.com"
}

###

### 4. Eliminar un usuario (DELETE)
DELETE https://special-space-giggle-g46qxpxg5667c9jvp-3000.app.github.dev/usuarios/




### EVIDENCIA 5.A: Probar el bloqueo del backend (DEBE DAR 401 UNAUTHORIZED)
# Esta petición va al servidor de Node.js (crispy-barnacle) para ver cómo el middleware bloquea el acceso
GET https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/usuarios/

###

### 1. Intentar registrar un usuario nuevo en el Backend
# Mandamos los datos a Node.js para que use Bcrypt antes de guardarlo en MySQL
POST https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/usuarios/
Content-Type: application/json

{
    "nombre": "Juan_Sicrititos",
    "correo": "seto@ddddddssdds.com",
    "password": "Contraseña_encrip"
}

###

#### LOGIN
POST https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/api/login
Content-Type: application/json

{
   "correo": "seto@ddddddssdds.com",
    "password": "Contraseña_encrip"
}

###

### EVIDENCIA 5.B: Acceder a la ruta con el Token obtenido
GET https://crispy-barnacle-4j96vx6wj452q6vp-3000.app.github.dev/usuarios/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImNvcnJlbyI6InNldG9AZGRkZGRkc3NkZHMuY29tIiwiaWF0IjoxNzgxMjQ0OTU3LCJleHAiOjE3ODEyNDg1NTd9.znnueZI5SrWxgSD4Q7rBCE1DOJ1rsbyVfMThfJnmrE0